# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/inss/contribution_salary_ranges', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Inss::ContributionSalaryRange. As you add validations to Inss::ContributionSalaryRange, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Inss::ContributionSalaryRange.create! valid_attributes
      get inss_contribution_salary_ranges_url
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      contribution_salary_range = Inss::ContributionSalaryRange.create! valid_attributes
      get inss_contribution_salary_range_url(contribution_salary_range)
      expect(response).to be_successful
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_inss_contribution_salary_range_url
      expect(response).to be_successful
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      contribution_salary_range = Inss::ContributionSalaryRange.create! valid_attributes
      get edit_inss_contribution_salary_range_url(contribution_salary_range)
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Inss::ContributionSalaryRange' do
        expect do
          post inss_contribution_salary_ranges_url, params: { inss_contribution_salary_range: valid_attributes }
        end.to change(Inss::ContributionSalaryRange, :count).by(1)
      end

      it 'redirects to the created inss_contribution_salary_range' do
        post inss_contribution_salary_ranges_url, params: { inss_contribution_salary_range: valid_attributes }
        expect(response).to redirect_to(inss_contribution_salary_range_url(Inss::ContributionSalaryRange.last))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Inss::ContributionSalaryRange' do
        expect do
          post inss_contribution_salary_ranges_url, params: { inss_contribution_salary_range: invalid_attributes }
        end.to change(Inss::ContributionSalaryRange, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post inss_contribution_salary_ranges_url, params: { inss_contribution_salary_range: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested inss_contribution_salary_range' do
        contribution_salary_range = Inss::ContributionSalaryRange.create! valid_attributes
        patch inss_contribution_salary_range_url(contribution_salary_range),
              params: { inss_contribution_salary_range: new_attributes }
        contribution_salary_range.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the inss_contribution_salary_range' do
        contribution_salary_range = Inss::ContributionSalaryRange.create! valid_attributes
        patch inss_contribution_salary_range_url(contribution_salary_range),
              params: { inss_contribution_salary_range: new_attributes }
        contribution_salary_range.reload
        expect(response).to redirect_to(inss_contribution_salary_range_url(contribution_salary_range))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        contribution_salary_range = Inss::ContributionSalaryRange.create! valid_attributes
        patch inss_contribution_salary_range_url(contribution_salary_range),
              params: { inss_contribution_salary_range: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested inss_contribution_salary_range' do
      contribution_salary_range = Inss::ContributionSalaryRange.create! valid_attributes
      expect do
        delete inss_contribution_salary_range_url(contribution_salary_range)
      end.to change(Inss::ContributionSalaryRange, :count).by(-1)
    end

    it 'redirects to the inss_contribution_salary_ranges list' do
      contribution_salary_range = Inss::ContributionSalaryRange.create! valid_attributes
      delete inss_contribution_salary_range_url(contribution_salary_range)
      expect(response).to redirect_to(inss_contribution_salary_ranges_url)
    end
  end
end
