require:
  - rubocop-rails
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20
  Exclude:
    - spec/**/*
    - db/**/*

Metrics/AbcSize:
  Enabled: true
  Exclude:
    - spec/**/*
    - db/**/*

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - db/**/*

Style/ClassAndModuleChildren:
  Enabled: false

Metrics/ParameterLists:
  Enabled: true
  Exclude:
    - app/concepts/**/*

RSpec/ExampleLength:
  Max: 10

RSpec/MultipleExpectations:
  Max: 10

Lint/UnreachableCode:
  Exclude:
    - "*/**/concepts/**/operation/**/*"
Style/SignalException:
  Exclude:
    - "*/**/concepts/**/operation/**/*"
