version: "3.8"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  db:
    image: postgres:14.2-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    command: "postgres -c 'max_connections=500'"
    environment:
      POSTGRES_DB: desconto_inss_development
      POSTGRES_USER: desconto_inss
      POSTGRES_PASSWORD: 254013nc!
    ports:
      - "5432:5432"
volumes:
  postgres_data: {}
networks:
  default:
    name: desconto-inss
